### ISSUE TITLE
License copyright is not filled in

### ISSUE THREAD

**Issue by chriscorcimiglia** [cablelabs/adrenaline-docs#91]
The license copyright info is not yet filled in.

<img width="938" alt="Screen Shot 2020-07-09 at 3 14 54 PM" src="https://user-images.githubusercontent.com/647151/87081294-16b0f480-c1f7-11ea-86de-04e240a3f65a.png">

As an aside, license usually reside with the code itself, so it might make sense to only manage it in the GitHub repo.

**Comment by cstuart7** [comment]
Please replace copyright template with:

  Copyright 2018 ARICENT HOLDINGS LUXEMBOURG S.à.r.l. and Cable Television Laboratories, Inc.
